// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6a0KVPQ5cxOMgAX65cuoT9uZyoPGjAWw',
    appId: '1:631918641698:web:8ee03cd56222c99bb9807b',
    messagingSenderId: '631918641698',
    projectId: 'aparna-education',
    authDomain: 'aparna-education.firebaseapp.com',
    storageBucket: 'aparna-education.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmRVYtZp2yB-kbfbPS1WRLaJdidvpha1M',
    appId: '1:631918641698:android:202513268cf50c75b9807b',
    messagingSenderId: '631918641698',
    projectId: 'aparna-education',
    storageBucket: 'aparna-education.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3ee_CrEd6Wn0Q-Jmmguxa9o1tUJYU-C0',
    appId: '1:631918641698:ios:50d4aaa19749c5f2b9807b',
    messagingSenderId: '631918641698',
    projectId: 'aparna-education',
    storageBucket: 'aparna-education.appspot.com',
    iosBundleId: 'com.example.aparnaEducation',
  );

}