// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcHu1mnccO23EINrbGkEo60V5Eyuq9A_0',
    appId: '1:373276967727:android:e8e2adc3207ccf2736d7da',
    messagingSenderId: '373276967727',
    projectId: 'dhairya-442fd',
    authDomain: 'dhairya-442fd.firebaseapp.com',
    storageBucket: 'dhairya-442fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbi60Yq-8dulKvEX-JL3uy17xDb3wizrY',
    appId: '1:373276967727:android:7dc9ffd2e5ab1f8236d7da',
    messagingSenderId: '373276967727',
    projectId: 'dhairya-442fd',
    storageBucket: 'dhairya-442fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADq_y6B_Tv8xgILOnYTfNWVMZPUdNVyeg',
    appId: '1:373276967727:ios:546fce7e5180c5df36d7da',
    messagingSenderId: '373276967727',
    projectId: 'dhairya-442fd',
    storageBucket: 'dhairya-442fd.firebasestorage.app',
    iosBundleId: 'com.example.aparnaEducation',
  );
}
